---
server:
    install: '1'
    packages: [git, htop]
    timezone: UTC
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: masput, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: localhost
mongodb:
    install: '1'
php:
    install: '1'
    ppa: php
    packages: [php5.6-cli, php5.6-intl, php5.6-mcrypt, php-pear, php5.6-curl, php5.6-imagick, php5.6-cgi, php5.6-common, php5.6-fpm, php5.6-xdebug, php5.6-xsl, php5.6-mbstring, php5.6-mongo]
    peclpackages: [mongo]
xdebug:
    install: '1'
composer:
    install: '1'

