---
- name: Install short_open_tag php.ini
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp='short_open_tag ='
              line='short_open_tag = On'

- name: Enable mbstring php.ini
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp='extension=php_mbstring.dll'
              line='extension=php_mbstring.dll'

- name: Enable exif php.ini
  lineinfile: dest=/etc/php/5.6/apache2/php.ini
              regexp='extension=php_exif.dll'
              line='extension=php_exif.dll'
